#!/bin/bash
# Real-time Training Progress Monitor

echo "╔════════════════════════════════════════════════════════════════════════════════╗"
echo "║                                                                                ║"
echo "║          M3 OAPR 50-Epoch Training on COCO - LIVE PROGRESS MONITOR            ║"
echo "║                                                                                ║"
echo "╚════════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "TRAINING STATUS:"
echo "───────────────────────────────────────────────────────────────────────────────"
tail -20 /Users/saad/.cursor/projects/Users-saad-Downloads-oapr-pose/terminals/554710.txt | grep -E "Epoch|Loss|LR|Accuracy|AP|Distance" || echo "Still initializing..."
echo ""
echo "───────────────────────────────────────────────────────────────────────────────"
echo ""
echo "RESULTS LOCATION:"
echo "  Output Log:        m3_coco_50epochs_full_results.log"
echo "  Training Log:      logs/oapr_m3/train_*.log"
echo "  Checkpoint:        checkpoints/oapr_m3/best.pth"
echo ""
echo "EXPECTED TIMELINE:"
echo "  Epochs 1-10:     3-4 hours"
echo "  Epochs 11-30:    6-8 hours"
echo "  Epochs 31-50:    8-10 hours"
echo "  Total:           17-22 hours (CPU)"
echo ""
echo "WHAT YOU'LL SEE:"
echo "  ✓ Per-epoch training loss"
echo "  ✓ Per-epoch validation accuracy"
echo "  ✓ Per-epoch AP (Average Precision)"
echo "  ✓ Distance metrics"
echo "  ✓ Learning rate schedule"
echo ""
echo "To monitor in another terminal, run:"
echo "  tail -f m3_coco_50epochs_full_results.log"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
